import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/home.module.scss'

import Input from '@/components/ui/Input'
import { Button } from '@/components/ui/Button'
import Link from 'next/link'
import { FormEvent, useContext, useState } from 'react'
import { AuthContext } from '../../contexts/AuthContext'



export default function Home() {

  const { signIn } = useContext(AuthContext);

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleLogin(event: FormEvent) {
    event.preventDefault();

    let data = {
      email,
      password
    }
    await signIn(data)
  }

  return (
    <>
      <Head>
        <title>Project PizzA</title>
        <meta name="description" content="Generated by - WSS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.containerCenter}>
          <Image
            src="/logo.svg"
            alt="Logo Sujeito Pizzaria"
            width={100}
            height={24}
            priority />
          <div className={styles.login}>
            <form onSubmit={handleLogin}>
              <Input
                placeholder='Digite seu email'
                type='text'
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <Input
                placeholder='Sua senha'
                type='password'
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />

              <Button
                type="submit"
                loading={false}
              >
                Acessar
              </Button>
            </form>
            <Link href="/signup" className={styles.text}>
              Não possui conta? Cadastre-se
              {/* <a className={styles.text}>Não possui conta? Cadastre-se</a> */}
            </Link>
          </div>
        </div>

      </main>
    </>
  )
}
